### ISSUE TITLE
まとめられるかも

### ISSUE THREAD

**Issue by C0A21015** [c0a2107793/ProjExD#6]
https://github.com/c0a2107793/ProjExD/blob/41ec79b38facce74fe35c6d85fd71015d9860e78/Ex03/maze.py#L18
if maze_lst[mx][my] == 0: （またはelse:）使えばまとめられるかも

**Comment by c0a2107793** [comment]
そのような方法をとると、スタート位置の画像も変わってしまうため、変更は致しませんでした。ご指摘ありがとうございます。
