### ISSUE TITLE
変数に説明が欲しい

### ISSUE THREAD

**Issue by C0A21015** [c0a2107793/ProjExD#8]
https://github.com/c0a2107793/ProjExD/blob/462aa80353dc70c09f50d8ccc8d7730ffa6ec418/Ex04/dodge_bomb.py#L20
きれいにできていいとおもいます。強いていうなら追加した変数に説明が欲しい

**Comment by c0a2107793** [comment]
この変数は、実装したかったが出来なかった変数でしたので、消去させていただきました。ご指摘ありがとうございます。
